package com.mdkproject.mdk2019.entity;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_id
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String areaNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_province
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String areaProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_city
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String areaCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_district
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String areaDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.create_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.update_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.createby
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String createby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_id
     *
     * @return the value of tb_area.area_id
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_id
     *
     * @param areaId the value for tb_area.area_id
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_num
     *
     * @return the value of tb_area.area_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getAreaNum() {
        return areaNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_num
     *
     * @param areaNum the value for tb_area.area_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setAreaNum(String areaNum) {
        this.areaNum = areaNum == null ? null : areaNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_province
     *
     * @return the value of tb_area.area_province
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getAreaProvince() {
        return areaProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_province
     *
     * @param areaProvince the value for tb_area.area_province
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setAreaProvince(String areaProvince) {
        this.areaProvince = areaProvince == null ? null : areaProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_city
     *
     * @return the value of tb_area.area_city
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getAreaCity() {
        return areaCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_city
     *
     * @param areaCity the value for tb_area.area_city
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setAreaCity(String areaCity) {
        this.areaCity = areaCity == null ? null : areaCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_district
     *
     * @return the value of tb_area.area_district
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getAreaDistrict() {
        return areaDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_district
     *
     * @param areaDistrict the value for tb_area.area_district
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setAreaDistrict(String areaDistrict) {
        this.areaDistrict = areaDistrict == null ? null : areaDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.create_time
     *
     * @return the value of tb_area.create_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.create_time
     *
     * @param createTime the value for tb_area.create_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.update_time
     *
     * @return the value of tb_area.update_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.update_time
     *
     * @param updateTime the value for tb_area.update_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.createby
     *
     * @return the value of tb_area.createby
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.createby
     *
     * @param createby the value for tb_area.createby
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }
}