package com.mdkproject.mdk2019.entity;

public class DeptPerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.dept_id
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.dept_name
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.dept_code
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.dept_pname
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String deptPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.dept_gender
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String deptGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.dept_idcard
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String deptIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.dept_phone
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String deptPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.create_time
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.update_time
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.dept_id
     *
     * @return the value of tb_dept.dept_id
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.dept_id
     *
     * @param deptId the value for tb_dept.dept_id
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.dept_name
     *
     * @return the value of tb_dept.dept_name
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.dept_name
     *
     * @param deptName the value for tb_dept.dept_name
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.dept_code
     *
     * @return the value of tb_dept.dept_code
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.dept_code
     *
     * @param deptCode the value for tb_dept.dept_code
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.dept_pname
     *
     * @return the value of tb_dept.dept_pname
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getDeptPname() {
        return deptPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.dept_pname
     *
     * @param deptPname the value for tb_dept.dept_pname
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setDeptPname(String deptPname) {
        this.deptPname = deptPname == null ? null : deptPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.dept_gender
     *
     * @return the value of tb_dept.dept_gender
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getDeptGender() {
        return deptGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.dept_gender
     *
     * @param deptGender the value for tb_dept.dept_gender
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setDeptGender(String deptGender) {
        this.deptGender = deptGender == null ? null : deptGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.dept_idcard
     *
     * @return the value of tb_dept.dept_idcard
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getDeptIdcard() {
        return deptIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.dept_idcard
     *
     * @param deptIdcard the value for tb_dept.dept_idcard
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setDeptIdcard(String deptIdcard) {
        this.deptIdcard = deptIdcard == null ? null : deptIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.dept_phone
     *
     * @return the value of tb_dept.dept_phone
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getDeptPhone() {
        return deptPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.dept_phone
     *
     * @param deptPhone the value for tb_dept.dept_phone
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setDeptPhone(String deptPhone) {
        this.deptPhone = deptPhone == null ? null : deptPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.create_time
     *
     * @return the value of tb_dept.create_time
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.create_time
     *
     * @param createTime the value for tb_dept.create_time
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.update_time
     *
     * @return the value of tb_dept.update_time
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.update_time
     *
     * @param updateTime the value for tb_dept.update_time
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}