package com.mdkproject.mdk2019.entity;

public class DeptOrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.dept_id
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.dept_name
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.dept_code
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.hostpital_num
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String hostpitalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.hostpital_code
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String hostpitalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.p_name
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.p_sex
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String pSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.p_age
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private Integer pAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.p_idcard
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String pIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.p_photo
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String pPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.status
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.p_telphone
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String pTelphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.record_date
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.create_time
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_deptorder.update_time
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.dept_id
     *
     * @return the value of tb_deptorder.dept_id
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.dept_id
     *
     * @param deptId the value for tb_deptorder.dept_id
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.dept_name
     *
     * @return the value of tb_deptorder.dept_name
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.dept_name
     *
     * @param deptName the value for tb_deptorder.dept_name
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.dept_code
     *
     * @return the value of tb_deptorder.dept_code
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.dept_code
     *
     * @param deptCode the value for tb_deptorder.dept_code
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.hostpital_num
     *
     * @return the value of tb_deptorder.hostpital_num
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getHostpitalNum() {
        return hostpitalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.hostpital_num
     *
     * @param hostpitalNum the value for tb_deptorder.hostpital_num
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setHostpitalNum(String hostpitalNum) {
        this.hostpitalNum = hostpitalNum == null ? null : hostpitalNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.hostpital_code
     *
     * @return the value of tb_deptorder.hostpital_code
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getHostpitalCode() {
        return hostpitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.hostpital_code
     *
     * @param hostpitalCode the value for tb_deptorder.hostpital_code
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setHostpitalCode(String hostpitalCode) {
        this.hostpitalCode = hostpitalCode == null ? null : hostpitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.p_name
     *
     * @return the value of tb_deptorder.p_name
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.p_name
     *
     * @param pName the value for tb_deptorder.p_name
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.p_sex
     *
     * @return the value of tb_deptorder.p_sex
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getpSex() {
        return pSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.p_sex
     *
     * @param pSex the value for tb_deptorder.p_sex
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setpSex(String pSex) {
        this.pSex = pSex == null ? null : pSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.p_age
     *
     * @return the value of tb_deptorder.p_age
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public Integer getpAge() {
        return pAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.p_age
     *
     * @param pAge the value for tb_deptorder.p_age
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setpAge(Integer pAge) {
        this.pAge = pAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.p_idcard
     *
     * @return the value of tb_deptorder.p_idcard
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getpIdcard() {
        return pIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.p_idcard
     *
     * @param pIdcard the value for tb_deptorder.p_idcard
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setpIdcard(String pIdcard) {
        this.pIdcard = pIdcard == null ? null : pIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.p_photo
     *
     * @return the value of tb_deptorder.p_photo
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getpPhoto() {
        return pPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.p_photo
     *
     * @param pPhoto the value for tb_deptorder.p_photo
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setpPhoto(String pPhoto) {
        this.pPhoto = pPhoto == null ? null : pPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.status
     *
     * @return the value of tb_deptorder.status
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.status
     *
     * @param status the value for tb_deptorder.status
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.p_telphone
     *
     * @return the value of tb_deptorder.p_telphone
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getpTelphone() {
        return pTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.p_telphone
     *
     * @param pTelphone the value for tb_deptorder.p_telphone
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setpTelphone(String pTelphone) {
        this.pTelphone = pTelphone == null ? null : pTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.record_date
     *
     * @return the value of tb_deptorder.record_date
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.record_date
     *
     * @param recordDate the value for tb_deptorder.record_date
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate == null ? null : recordDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.create_time
     *
     * @return the value of tb_deptorder.create_time
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.create_time
     *
     * @param createTime the value for tb_deptorder.create_time
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_deptorder.update_time
     *
     * @return the value of tb_deptorder.update_time
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_deptorder.update_time
     *
     * @param updateTime the value for tb_deptorder.update_time
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}