package com.mdkproject.mdk2019.entity;

import javax.persistence.Transient;

public class DeptOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept_order.dept_id
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept_order.dept_organization
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    private String deptOrganization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept_order.dept_name
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept_order.dept_code
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    private String deptCode;

    @Transient
    private int daycount;

    public int getDaycount() {
        return daycount;
    }

    public void setDaycount(int daycount) {
        this.daycount = daycount;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept_order.dept_tel
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    private String deptTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept_order.create_time
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept_order.update_time
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept_order.dept_id
     *
     * @return the value of tb_dept_order.dept_id
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept_order.dept_id
     *
     * @param deptId the value for tb_dept_order.dept_id
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept_order.dept_organization
     *
     * @return the value of tb_dept_order.dept_organization
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public String getDeptOrganization() {
        return deptOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept_order.dept_organization
     *
     * @param deptOrganization the value for tb_dept_order.dept_organization
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public void setDeptOrganization(String deptOrganization) {
        this.deptOrganization = deptOrganization == null ? null : deptOrganization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept_order.dept_name
     *
     * @return the value of tb_dept_order.dept_name
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept_order.dept_name
     *
     * @param deptName the value for tb_dept_order.dept_name
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept_order.dept_code
     *
     * @return the value of tb_dept_order.dept_code
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept_order.dept_code
     *
     * @param deptCode the value for tb_dept_order.dept_code
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept_order.dept_tel
     *
     * @return the value of tb_dept_order.dept_tel
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public String getDeptTel() {
        return deptTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept_order.dept_tel
     *
     * @param deptTel the value for tb_dept_order.dept_tel
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public void setDeptTel(String deptTel) {
        this.deptTel = deptTel == null ? null : deptTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept_order.create_time
     *
     * @return the value of tb_dept_order.create_time
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept_order.create_time
     *
     * @param createTime the value for tb_dept_order.create_time
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept_order.update_time
     *
     * @return the value of tb_dept_order.update_time
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept_order.update_time
     *
     * @param updateTime the value for tb_dept_order.update_time
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}