package com.mdkproject.mdk2019.entity;

public class Hospital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_id
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_name
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String hospitalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_gz
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String hospitalGz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_province
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String hospitalProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_city
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String hospitalCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_district
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String hospitalDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.hospital_address
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String hospitalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.area_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    //private String areaNum;










    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.create_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hospital.update_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_id
     *
     * @return the value of tb_hospital.hospital_id
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_id
     *
     * @param hospitalId the value for tb_hospital.hospital_id
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_name
     *
     * @return the value of tb_hospital.hospital_name
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_name
     *
     * @param hospitalName the value for tb_hospital.hospital_name
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_num
     *
     * @return the value of tb_hospital.hospital_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getHospitalNum() {
        return hospitalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_num
     *
     * @param hospitalNum the value for tb_hospital.hospital_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalNum(String hospitalNum) {
        this.hospitalNum = hospitalNum == null ? null : hospitalNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_gz
     *
     * @return the value of tb_hospital.hospital_gz
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getHospitalGz() {
        return hospitalGz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_gz
     *
     * @param hospitalGz the value for tb_hospital.hospital_gz
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalGz(String hospitalGz) {
        this.hospitalGz = hospitalGz == null ? null : hospitalGz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_province
     *
     * @return the value of tb_hospital.hospital_province
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getHospitalProvince() {
        return hospitalProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_province
     *
     * @param hospitalProvince the value for tb_hospital.hospital_province
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalProvince(String hospitalProvince) {
        this.hospitalProvince = hospitalProvince == null ? null : hospitalProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_city
     *
     * @return the value of tb_hospital.hospital_city
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getHospitalCity() {
        return hospitalCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_city
     *
     * @param hospitalCity the value for tb_hospital.hospital_city
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalCity(String hospitalCity) {
        this.hospitalCity = hospitalCity == null ? null : hospitalCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_district
     *
     * @return the value of tb_hospital.hospital_district
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getHospitalDistrict() {
        return hospitalDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_district
     *
     * @param hospitalDistrict the value for tb_hospital.hospital_district
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalDistrict(String hospitalDistrict) {
        this.hospitalDistrict = hospitalDistrict == null ? null : hospitalDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.hospital_address
     *
     * @return the value of tb_hospital.hospital_address
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getHospitalAddress() {
        return hospitalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.hospital_address
     *
     * @param hospitalAddress the value for tb_hospital.hospital_address
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setHospitalAddress(String hospitalAddress) {
        this.hospitalAddress = hospitalAddress == null ? null : hospitalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.area_num
     *
     * @return the value of tb_hospital.area_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
  /*  public String getAreaNum() {
        return areaNum;
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.area_num
     *
     * @param areaNum the value for tb_hospital.area_num
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    /*public void setAreaNum(String areaNum) {
        this.areaNum = areaNum == null ? null : areaNum.trim();
    }*/

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.create_time
     *
     * @return the value of tb_hospital.create_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.create_time
     *
     * @param createTime the value for tb_hospital.create_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hospital.update_time
     *
     * @return the value of tb_hospital.update_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_hospital.update_time
     *
     * @param updateTime the value for tb_hospital.update_time
     *
     * @mbg.generated Tue Apr 02 16:50:27 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}