package com.mdkproject.mdk2019.entity;

public class JieLun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.id
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String jielun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.doctor
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String doctor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.yijian
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String yijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.gz
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String gz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.create_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.update_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String personIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.status
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.no_project
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String noProject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.hearth_cardid
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String hearthCardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.start_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jielun.end_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    private String endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.id
     *
     * @return the value of tb_jielun.id
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.id
     *
     * @param id the value for tb_jielun.id
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.jielun
     *
     * @return the value of tb_jielun.jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getJielun() {
        return jielun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.jielun
     *
     * @param jielun the value for tb_jielun.jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setJielun(String jielun) {
        this.jielun = jielun == null ? null : jielun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.doctor
     *
     * @return the value of tb_jielun.doctor
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.doctor
     *
     * @param doctor the value for tb_jielun.doctor
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.yijian
     *
     * @return the value of tb_jielun.yijian
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getYijian() {
        return yijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.yijian
     *
     * @param yijian the value for tb_jielun.yijian
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setYijian(String yijian) {
        this.yijian = yijian == null ? null : yijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.gz
     *
     * @return the value of tb_jielun.gz
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getGz() {
        return gz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.gz
     *
     * @param gz the value for tb_jielun.gz
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setGz(String gz) {
        this.gz = gz == null ? null : gz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.create_time
     *
     * @return the value of tb_jielun.create_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.create_time
     *
     * @param createTime the value for tb_jielun.create_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.update_time
     *
     * @return the value of tb_jielun.update_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.update_time
     *
     * @param updateTime the value for tb_jielun.update_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.person_idcard
     *
     * @return the value of tb_jielun.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getPersonIdcard() {
        return personIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.person_idcard
     *
     * @param personIdcard the value for tb_jielun.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setPersonIdcard(String personIdcard) {
        this.personIdcard = personIdcard == null ? null : personIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.status
     *
     * @return the value of tb_jielun.status
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.status
     *
     * @param status the value for tb_jielun.status
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.no_project
     *
     * @return the value of tb_jielun.no_project
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getNoProject() {
        return noProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.no_project
     *
     * @param noProject the value for tb_jielun.no_project
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setNoProject(String noProject) {
        this.noProject = noProject == null ? null : noProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.hearth_cardid
     *
     * @return the value of tb_jielun.hearth_cardid
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getHearthCardid() {
        return hearthCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.hearth_cardid
     *
     * @param hearthCardid the value for tb_jielun.hearth_cardid
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setHearthCardid(String hearthCardid) {
        this.hearthCardid = hearthCardid == null ? null : hearthCardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.start_time
     *
     * @return the value of tb_jielun.start_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.start_time
     *
     * @param startTime the value for tb_jielun.start_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jielun.end_time
     *
     * @return the value of tb_jielun.end_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jielun.end_time
     *
     * @param endTime the value for tb_jielun.end_time
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }
}