package com.mdkproject.mdk2019.entity;

public class Lab {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.lab_id
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private Integer labId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.person_idcard
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String personIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.liji
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String liji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.shanghan
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String shanghan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.alt
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String alt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.anti_hav
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String antiHav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.anti_hev
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String antiHev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.doctor
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String doctor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.qt
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String qt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.create_time
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_lab.update_time
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.lab_id
     *
     * @return the value of tb_lab.lab_id
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public Integer getLabId() {
        return labId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.lab_id
     *
     * @param labId the value for tb_lab.lab_id
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setLabId(Integer labId) {
        this.labId = labId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.person_idcard
     *
     * @return the value of tb_lab.person_idcard
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getPersonIdcard() {
        return personIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.person_idcard
     *
     * @param personIdcard the value for tb_lab.person_idcard
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setPersonIdcard(String personIdcard) {
        this.personIdcard = personIdcard == null ? null : personIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.liji
     *
     * @return the value of tb_lab.liji
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getLiji() {
        return liji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.liji
     *
     * @param liji the value for tb_lab.liji
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setLiji(String liji) {
        this.liji = liji == null ? null : liji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.shanghan
     *
     * @return the value of tb_lab.shanghan
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getShanghan() {
        return shanghan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.shanghan
     *
     * @param shanghan the value for tb_lab.shanghan
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setShanghan(String shanghan) {
        this.shanghan = shanghan == null ? null : shanghan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.alt
     *
     * @return the value of tb_lab.alt
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.alt
     *
     * @param alt the value for tb_lab.alt
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setAlt(String alt) {
        this.alt = alt == null ? null : alt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.anti_hav
     *
     * @return the value of tb_lab.anti_hav
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getAntiHav() {
        return antiHav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.anti_hav
     *
     * @param antiHav the value for tb_lab.anti_hav
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setAntiHav(String antiHav) {
        this.antiHav = antiHav == null ? null : antiHav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.anti_hev
     *
     * @return the value of tb_lab.anti_hev
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getAntiHev() {
        return antiHev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.anti_hev
     *
     * @param antiHev the value for tb_lab.anti_hev
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setAntiHev(String antiHev) {
        this.antiHev = antiHev == null ? null : antiHev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.doctor
     *
     * @return the value of tb_lab.doctor
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.doctor
     *
     * @param doctor the value for tb_lab.doctor
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.qt
     *
     * @return the value of tb_lab.qt
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.qt
     *
     * @param qt the value for tb_lab.qt
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setQt(String qt) {
        this.qt = qt == null ? null : qt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.create_time
     *
     * @return the value of tb_lab.create_time
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.create_time
     *
     * @param createTime the value for tb_lab.create_time
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_lab.update_time
     *
     * @return the value of tb_lab.update_time
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_lab.update_time
     *
     * @param updateTime the value for tb_lab.update_time
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}