package com.mdkproject.mdk2019.entity;

public class SicknessHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.sickness_id
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private Integer sicknessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String personIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.ganyan
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String ganyan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.liji
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String liji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.shanghan
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String shanghan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.feijiehe
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String feijiehe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.pifubing
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String pifubing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.qt
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String qt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.create_time
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sickness_history.update_time
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.sickness_id
     *
     * @return the value of tb_sickness_history.sickness_id
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public Integer getSicknessId() {
        return sicknessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.sickness_id
     *
     * @param sicknessId the value for tb_sickness_history.sickness_id
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setSicknessId(Integer sicknessId) {
        this.sicknessId = sicknessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.person_idcard
     *
     * @return the value of tb_sickness_history.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getPersonIdcard() {
        return personIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.person_idcard
     *
     * @param personIdcard the value for tb_sickness_history.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setPersonIdcard(String personIdcard) {
        this.personIdcard = personIdcard == null ? null : personIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.ganyan
     *
     * @return the value of tb_sickness_history.ganyan
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getGanyan() {
        return ganyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.ganyan
     *
     * @param ganyan the value for tb_sickness_history.ganyan
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setGanyan(String ganyan) {
        this.ganyan = ganyan == null ? null : ganyan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.liji
     *
     * @return the value of tb_sickness_history.liji
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getLiji() {
        return liji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.liji
     *
     * @param liji the value for tb_sickness_history.liji
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setLiji(String liji) {
        this.liji = liji == null ? null : liji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.shanghan
     *
     * @return the value of tb_sickness_history.shanghan
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getShanghan() {
        return shanghan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.shanghan
     *
     * @param shanghan the value for tb_sickness_history.shanghan
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setShanghan(String shanghan) {
        this.shanghan = shanghan == null ? null : shanghan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.feijiehe
     *
     * @return the value of tb_sickness_history.feijiehe
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getFeijiehe() {
        return feijiehe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.feijiehe
     *
     * @param feijiehe the value for tb_sickness_history.feijiehe
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setFeijiehe(String feijiehe) {
        this.feijiehe = feijiehe == null ? null : feijiehe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.pifubing
     *
     * @return the value of tb_sickness_history.pifubing
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getPifubing() {
        return pifubing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.pifubing
     *
     * @param pifubing the value for tb_sickness_history.pifubing
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setPifubing(String pifubing) {
        this.pifubing = pifubing == null ? null : pifubing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.qt
     *
     * @return the value of tb_sickness_history.qt
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.qt
     *
     * @param qt the value for tb_sickness_history.qt
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setQt(String qt) {
        this.qt = qt == null ? null : qt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.create_time
     *
     * @return the value of tb_sickness_history.create_time
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.create_time
     *
     * @param createTime the value for tb_sickness_history.create_time
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sickness_history.update_time
     *
     * @return the value of tb_sickness_history.update_time
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sickness_history.update_time
     *
     * @param updateTime the value for tb_sickness_history.update_time
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}