package com.mdkproject.mdk2019.entity;

public class Sign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.sign_id
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private Integer signId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String personIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.xin
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String xin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.gan
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String gan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.pi
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String pi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.fei
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String fei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.pifu
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String pifu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.qt
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String qt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.doctor
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String doctor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.create_time
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_sign.update_time
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.sign_id
     *
     * @return the value of tb_sign.sign_id
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public Integer getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.sign_id
     *
     * @param signId the value for tb_sign.sign_id
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setSignId(Integer signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.person_idcard
     *
     * @return the value of tb_sign.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getPersonIdcard() {
        return personIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.person_idcard
     *
     * @param personIdcard the value for tb_sign.person_idcard
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setPersonIdcard(String personIdcard) {
        this.personIdcard = personIdcard == null ? null : personIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.xin
     *
     * @return the value of tb_sign.xin
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getXin() {
        return xin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.xin
     *
     * @param xin the value for tb_sign.xin
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setXin(String xin) {
        this.xin = xin == null ? null : xin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.gan
     *
     * @return the value of tb_sign.gan
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getGan() {
        return gan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.gan
     *
     * @param gan the value for tb_sign.gan
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setGan(String gan) {
        this.gan = gan == null ? null : gan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.pi
     *
     * @return the value of tb_sign.pi
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getPi() {
        return pi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.pi
     *
     * @param pi the value for tb_sign.pi
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setPi(String pi) {
        this.pi = pi == null ? null : pi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.fei
     *
     * @return the value of tb_sign.fei
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getFei() {
        return fei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.fei
     *
     * @param fei the value for tb_sign.fei
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setFei(String fei) {
        this.fei = fei == null ? null : fei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.pifu
     *
     * @return the value of tb_sign.pifu
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getPifu() {
        return pifu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.pifu
     *
     * @param pifu the value for tb_sign.pifu
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setPifu(String pifu) {
        this.pifu = pifu == null ? null : pifu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.qt
     *
     * @return the value of tb_sign.qt
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.qt
     *
     * @param qt the value for tb_sign.qt
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setQt(String qt) {
        this.qt = qt == null ? null : qt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.doctor
     *
     * @return the value of tb_sign.doctor
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.doctor
     *
     * @param doctor the value for tb_sign.doctor
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.create_time
     *
     * @return the value of tb_sign.create_time
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.create_time
     *
     * @param createTime the value for tb_sign.create_time
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sign.update_time
     *
     * @return the value of tb_sign.update_time
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sign.update_time
     *
     * @param updateTime the value for tb_sign.update_time
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}