package com.mdkproject.mdk2019.entity;

public class Xpicture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_x_picture.x_id
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    private Integer xId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_x_picture.person_idcard
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    private String personIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_x_picture.x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    private String xPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_x_picture.doctor
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    private String doctor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_x_picture.create_time
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_x_picture.update_time
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_x_picture.x_id
     *
     * @return the value of tb_x_picture.x_id
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public Integer getxId() {
        return xId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_x_picture.x_id
     *
     * @param xId the value for tb_x_picture.x_id
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public void setxId(Integer xId) {
        this.xId = xId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_x_picture.person_idcard
     *
     * @return the value of tb_x_picture.person_idcard
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public String getPersonIdcard() {
        return personIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_x_picture.person_idcard
     *
     * @param personIdcard the value for tb_x_picture.person_idcard
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public void setPersonIdcard(String personIdcard) {
        this.personIdcard = personIdcard == null ? null : personIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_x_picture.x_picture
     *
     * @return the value of tb_x_picture.x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public String getxPicture() {
        return xPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_x_picture.x_picture
     *
     * @param xPicture the value for tb_x_picture.x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public void setxPicture(String xPicture) {
        this.xPicture = xPicture == null ? null : xPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_x_picture.doctor
     *
     * @return the value of tb_x_picture.doctor
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public String getDoctor() {
        return doctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_x_picture.doctor
     *
     * @param doctor the value for tb_x_picture.doctor
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public void setDoctor(String doctor) {
        this.doctor = doctor == null ? null : doctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_x_picture.create_time
     *
     * @return the value of tb_x_picture.create_time
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_x_picture.create_time
     *
     * @param createTime the value for tb_x_picture.create_time
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_x_picture.update_time
     *
     * @return the value of tb_x_picture.update_time
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_x_picture.update_time
     *
     * @param updateTime the value for tb_x_picture.update_time
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}