package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.DeptPerson;

import java.util.List;

public interface DeptPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    int insert(DeptPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    int insertSelective(DeptPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    DeptPerson selectByPrimaryKey(Integer deptId);
    //列表降序
    List<DeptPerson> listDeptPerson();
    //批量添加
    List<DeptPerson> insertBatch(List<DeptPerson> deptPerson);
    //根据身份证查询
    DeptPerson findByIdcard(String Idcard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    int updateByPrimaryKeySelective(DeptPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept
     *
     * @mbg.generated Tue Apr 09 09:54:50 CST 2019
     */
    int updateByPrimaryKey(DeptPerson record);
}