package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.DeptOrderInfo;

public interface DeptOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    int insert(DeptOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    int insertSelective(DeptOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    DeptOrderInfo selectByPrimaryKey(Integer deptId);

    //依据身份证号
    DeptOrderInfo selectByIdCard(String idCard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    int updateByPrimaryKeySelective(DeptOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Sat Apr 27 18:22:20 CST 2019
     */
    int updateByPrimaryKey(DeptOrderInfo record);
}