package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.DeptOrderExcel;

public interface DeptOrderExcelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Fri Apr 19 17:34:01 CST 2019
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Fri Apr 19 17:34:01 CST 2019
     */
    int insert(DeptOrderExcel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Fri Apr 19 17:34:01 CST 2019
     */
    int insertSelective(DeptOrderExcel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Fri Apr 19 17:34:01 CST 2019
     */
    DeptOrderExcel selectByPrimaryKey(Integer deptId);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Fri Apr 19 17:34:01 CST 2019
     */
    int updateByPrimaryKeySelective(DeptOrderExcel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_deptorder
     *
     * @mbg.generated Fri Apr 19 17:34:01 CST 2019
     */
    int updateByPrimaryKey(DeptOrderExcel record);


}