package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.DeptOrder;

import java.util.List;

public interface DeptOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept_order
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept_order
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    int insert(DeptOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept_order
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    int insertSelective(DeptOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept_order
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    DeptOrder selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept_order
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    int updateByPrimaryKeySelective(DeptOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dept_order
     *
     * @mbg.generated Wed Apr 03 09:20:55 CST 2019
     */
    int updateByPrimaryKey(DeptOrder record);


    //查询当日预约体检的单位个数
    int dayordernum(String nowdate);

    //查询近五天预约单位数
    List<DeptOrder> weektjnum();
}