package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.JieLun;

public interface JieLunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    int insert(JieLun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    int insertSelective(JieLun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    JieLun selectByPrimaryKey(Integer id);

    //体检表根据身份证号多表查询
    JieLun findByIdcard(String personIdcard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    int updateByPrimaryKeySelective(JieLun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jielun
     *
     * @mbg.generated Mon Apr 15 13:59:48 CST 2019
     */
    int updateByPrimaryKey(JieLun record);
}