package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.Lab;

public interface LabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lab
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    int deleteByPrimaryKey(Integer labId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lab
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    int insert(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lab
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    int insertSelective(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lab
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    Lab selectByPrimaryKey(Integer labId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lab
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    int updateByPrimaryKeySelective(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lab
     *
     * @mbg.generated Mon Apr 15 14:00:17 CST 2019
     */
    int updateByPrimaryKey(Lab record);

    Lab findByIdcard(String personIdcard);
}