package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.SicknessHistory;

public interface SicknessHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sickness_history
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    int deleteByPrimaryKey(Integer sicknessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sickness_history
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    int insert(SicknessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sickness_history
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    int insertSelective(SicknessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sickness_history
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    SicknessHistory selectByPrimaryKey(Integer sicknessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sickness_history
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    int updateByPrimaryKeySelective(SicknessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sickness_history
     *
     * @mbg.generated Mon Apr 15 13:36:24 CST 2019
     */
    int updateByPrimaryKey(SicknessHistory record);

    SicknessHistory findByIdcard(String personIdcard);
}