package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.Sign;

public interface SignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sign
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    int deleteByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sign
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    int insert(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sign
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    int insertSelective(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sign
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    Sign selectByPrimaryKey(Integer signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sign
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    int updateByPrimaryKeySelective(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sign
     *
     * @mbg.generated Mon Apr 15 13:36:58 CST 2019
     */
    int updateByPrimaryKey(Sign record);

    Sign findByIdcard(String personIdcard);
}