package com.mdkproject.mdk2019.dao;

import com.mdkproject.mdk2019.entity.Xpicture;

public interface XpictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    int deleteByPrimaryKey(Integer xId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    int insert(Xpicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    int insertSelective(Xpicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    Xpicture selectByPrimaryKey(Integer xId);

    Xpicture findByIdcard(String personIdcard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    int updateByPrimaryKeySelective(Xpicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_x_picture
     *
     * @mbg.generated Wed Apr 17 13:12:34 CST 2019
     */
    int updateByPrimaryKey(Xpicture record);
}